spring:
  application:
    name: jwt-spring-security
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
app:
  security:
    jwt:
      access-token-expiration: 86400000 # 24 hours for local testing, 15mins are recommended for prod
      refresh-token-expiration: 604800000
